### ISSUE TITLE
Error after uptdate 1.8.0

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-element#34]
Since I updated to version 1.8.0 i get the following Error: 

VM319:156 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at _inheritsLoose (<anonymous>:156:77)
    at <anonymous>:181:3
    at Object../node_modules/@biotope/element/lib/index.js (<anonymous>:271:2)
    at __webpack_require__ (<anonymous>:20:30)
    at Module../src/components/listUnordered/ts/listUnordered.ts (<anonymous>:3628:74)
    at __webpack_require__ (<anonymous>:20:30)
    at ./node_modules/@biotope/element/lib/attribute-name-mapper.js.Object.defineProperty.value (<anonymous>:84:18)
    at <anonymous>:87:10
    at DOMEval (jquery.js:111)

is there anything else I have to change for that update. In the Boilerplate for example?

**Comment by jurekbarth** [comment]
@tiagomapmarques is that fixed in 1.8.1?

**Comment by tiagomapmarques** [comment]
v1.8.1 was a bugfix for a previous bug that was still happening on some circumstances.
Nothing to do with this ticket.

**Comment by timomayer** [comment]
@tiagomapmarques can you look into that ticket today please. its important for the Siedle project it gets fixed otherwise the Siedle team is stuck. if there are conflicts with other projects today please ping me

**Comment by tiagomapmarques** [comment]
The bug was switching from `esnext` to `commonjs`. This causes the compiled code to be exported differently and thus some projects might have problems importing and using the code.

As for the solution, we should review our typings and exports to make sure we are exporting the Component class correctly on `commonjs`. IMO we should not revert to `esnext`.

**Comment by dweiger** [comment]
@tiagomapmarques Sadly that does not solve the Problem.
